### ISSUE TITLE
Can it be modified?

### ISSUE THREAD

**Issue by 343intact** [JoinedSenses/TF2-Disable-Sounds-Except-Voice#1]
Hey man! Didn't how else to contact you, except like this. Can this file be modified in a way, that let's to mute all in-game sounds and voices, except for an incoming trade offer guitar sound?

**Comment by JoinedSenses** [comment]
Yo. Maybe? My guess is you could use snd_showmixer in console to get the name of the sound when it plays, then add it to the txt config and tweak the sound parameters. I don't have an environment set up to test, so you'll have to experiment and compile using the instructions in the readme

**Comment by 343intact** [comment]
> Yo. Maybe? My guess is you could use snd_showmixer in console to get the name of the sound when it plays, then add it to the txt config and tweak the sound parameters. I don't have an environment set up to test, so you'll have to experiment and compile using the instructions in the readme

I already did it! I tweaked a bit and found out that trade sound is "notification" sound in "ui"! All I had to do is change voip to 0.0 and ui to 1.0. Also snd_showmixer or others did nothing, only snd_show 1 worked in solo with bots with sv_cheats on. Thank you for your work and your template

**Comment by 343intact** [comment]
If wait command also worked on trade servers - life would be a dream lol
